version: "3"
services:

    nginx-dev:
        container_name: nginx-dev
        restart: unless-stopped
        image: nginx:stable-alpine
        ports:
            - "80:80"
        command: >
            /bin/sh -c "envsubst '$${DOMAIN}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
        env_file:
            - ./.env
        volumes:
            - ./nginx/nginx.template:/etc/nginx/nginx.template:ro

            - ./_data/log:/var/log/nginx
            - ./_data/media:/var/www/media
            - ./_data/static:/var/www/static
        labels:
            - dev.orbstack.domains=*.local

    db:
        container_name: db
        build:
          context: ../backend
          dockerfile: ./compose/local/db/Dockerfile
        restart: unless-stopped
        volumes:
            - db:/var/lib/postgresql/data/
            - ../backend/db/backups:/backups
            - ../backend/sql/:/sql
        env_file:
            - ../backend/.envs/.local/.db
        ports:
            - "5432:5432"

    backend:
        container_name: backend
        build:
            context: ../backend
            dockerfile: ./compose/local/backend/Dockerfile
        command: /start
        restart: unless-stopped
        links:
            - 'nginx-dev:api.dev.mindat.org'
        depends_on:
            - db
            - nginx-dev
        env_file:
            - ../backend/.envs/.local/.backend
            - ../backend/.envs/.local/.db
        volumes:
            - ../backend:/app

            - ./_data/media:/app/media
            - ./_data/static:/app/static
        ports:
            - "8000:8000"
        labels:
            - dev.orbstack.domains=api.mineralogy.rocks.local

    keep-rocking:
        restart: unless-stopped
        depends_on:
             - backend
             - nginx-dev
             - sidecar
        links:
             - 'nginx-dev:api.${DOMAIN}.local'
        build:
            context: ../keep-rocking
            dockerfile: dev.Dockerfile
        env_file:
            - ../keep-rocking/.envs/.local/.env
            - ../keep-rocking/.envs/.prod/.env
        stdin_open: true
        volumes:
            - node_modules:/app/node_modules
            - ../keep-rocking:/app
            - ./_data/static:/var/www/static
        ports:
            - "8080:3000"
        labels:
            - dev.orbstack.domains=mineralogy.rocks.local

    sidecar:
        image: ghcr.io/getsentry/spotlight:latest
        container_name: spotlight
        restart: unless-stopped
        ports:
            - "8969:8969"
        links:
            - 'nginx-dev:${DOMAIN}.local'

    backend-mindat:
        build:
            context: ../mindatapi
            dockerfile: ./compose/local/backend/Dockerfile
        command: /start
        restart: unless-stopped
        depends_on:
              - mysql5
              - nginx-dev
        ports:
              - "8000:8000"
        env_file:
            - ../mindatapi/.envs/.local/.backend
            - ../mindatapi/.envs/.local/.db
        volumes:
            - ../mindatapi:/app

            - ../mindatapi/nginx/_data/media:/app/media
            - ../mindatapi/nginx/_data/static:/app/static

    mysql5:
        build:
            context: ../mindatapi
            dockerfile: ./compose/local/db/Dockerfile
        restart: unless-stopped
        volumes:
            - mysql5:/var/lib/mysql
            - ../mindatapi/db/backups:/backups
        env_file:
          - ../mindatapi/.envs/.local/.db
        ports:
            - "3306:3306"

volumes:
    node_modules:
    db:
    mysql5:
